// Ouzel by Elviss Strazdins

#ifndef OUZEL_CONFIG_H
#define OUZEL_CONFIG_H

#include "core/Platform.h"

#define OUZEL_DEVELOPER_NAME "org.ouzel"
#define OUZEL_APPLICATION_NAME "sample"

#define OUZEL_ENABLE_OPENGL 1
#define OUZEL_ENABLE_DIRECT3D11 1
#define OUZEL_ENABLE_METAL 1

#define OUZEL_ENABLE_OPENAL 1
#define OUZEL_ENABLE_DIRECTSOUND 1
#define OUZEL_ENABLE_XAUDIO2 1
#define OUZEL_ENABLE_OPENSL 1
#define OUZEL_ENABLE_COREAUDIO 1
#define OUZEL_ENABLE_ALSA 1

#endif // OUZEL_CONFIG_H
